name : Trending-engine
services:
  db:
    image: postgres:latest
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=prisma
     - POSTGRES_DB=Trending-engine_db
    ports:
    - 5433:5432
